FROM registry.cn-hangzhou.aliyuncs.com/litosrc/ubuntu-1804:latest
EXPOSE 7000 7001 9110
WORKDIR /workdir
ADD ./docker-entrypoint.sh /docker-entrypoint.sh
ADD ./dependence /tmp/dependence
ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD ["./frps", "-c", "/volume/config/frps.ini"]