version: '3.7'
services:
  frpserver:
    restart: always
    container_name: FrpServer
    image:
      frpserver:latest
    build:
      ./
    volumes:
      - /Volumes/DockerStore/FrpServer/config/:/volume/config/
      - /Volumes/DockerStore/FrpServer/log/:/volume/log/
      - /tmp/DockerStore/:/tmp/DockerStore/
      - /Volumes/DockerStore/DockerStore/SSL/:/etc/nginx/ssl/
    networks:
      - dockerstore
    ports:
      - "7000:7000"
      - "7001:7001"
      - "9110:442"
      - "9500-9599:9500-9599"

networks:
  dockerstore:
    external: true