FROM registry.cn-hangzhou.aliyuncs.com/litosrc/nginx-php7fpm:latest
EXPOSE 7000 7001 9110
WORKDIR /workdir
ADD ./docker-entrypoint.sh /docker-entrypoint.sh
ADD ./dependence /tmp/dependence
ADD dependence/default /etc/nginx/sites-available/default
ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD ["./frps", "-c", "/volume/config/frps.ini"]