FROM registry.cn-hangzhou.aliyuncs.com/litosrc/ds-ubuntu:latest
EXPOSE 80
RUN apt-get install php7.2 php7.2-fpm php7.2-dev php7.2-mysql php7.2-XML php7.2-mbstring php7.2-curl php7.2-gd php7.2-zip nginx -y
WORKDIR /workdir
ADD ./dependence/default /etc/nginx/sites-available/default
ADD ./dependence /tmp/dependence
RUN cp -f /tmp/dependence/docker-entrypoint.sh /
ENTRYPOINT [ "/docker-entrypoint.sh" ]