version: '3.7'
services:
  resiliosync:
    restart: always
    container_name: ResilioSync
    image:
      resiliosync:latest
    build:
      ./
    volumes:
      - /volume/ResilioSync:/volume
    ports:
      - "9101:9001"
      - "55555:55555"