version: '3.7'
services:
  resiliosync:
    restart: always
    container_name: ResilioSync
    image:
      resiliosync:latest
    build:
      ./
    volumes:
      - /Volumes/DockerStore/ResilioSync/config:/config
      - /Volumes/DockerStore/ResilioSync/emby:/emby
      - /Volumes/DockerStore/ResilioSync/data:/data
      - /Volumes/DockerStore/DockerStore/SSL/:/workdir/ssl/
    networks:
      - dockerstore
    ports:
      - "9101:9101"
      - "55555:55555"

networks:
  dockerstore:
    external: true