FROM registry.cn-hangzhou.aliyuncs.com/litosrc/phpfpm:7.2
EXPOSE 443
WORKDIR /workdir
ADD ./dependence /tmp/dependence
ADD docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD ["nginx", "-g", "daemon off;"]