version: '3.7'
services:
  php72:
    restart: always
    container_name: PHP72
    image:
      php72:latest
    build:
      ./
    volumes:
      - ~/DockerStore/Volumes/PHP72/config/sites-available/:/etc/nginx/sites-available/
      - ~/DockerStore/Volumes/PHP72/config/php-fpm/:/etc/php/7.2/fpm/
      - ~/DockerStore/Volumes/PHP72/workdir/:/workdir/
    ports:
      - "9107:80"