version: '3.7'
services:
  emby:
    restart: always
    container_name: Emby
    image:
      emby:latest
    build:
      ./
    volumes:
      - /Volumes/DockerStore/Emby/config:/config
      - /Volumes/DockerStore/Emby/data:/data/Emby
      - /Volumes/DockerStore/ResilioSync/Download/Emby:/data/ResilioSync
      - /Volumes/DockerStore/Aria2/Download/Emby:/data/Aria2
      - /Volumes/DockerStore/DockerStore/SSL/:/etc/nginx/ssl/
    networks:
      - dockerstore
    ports:
      - "9117:8920"
    environment:
      TZ: "Asia/Shanghai"

networks:
  dockerstore:
    external: true