FROM registry.cn-hangzhou.aliyuncs.com/litosrc/ubuntu:18.04
WORKDIR /workdir
ADD ./dependence /tmp/dependence
ADD ./docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD ["./coredns","-dns.port=53","-conf","/workdir/config/Corefile"]