parameters:
#    eugef_php_red_expert_angular.example.class: Eugef\PhpRedExpert\AngularBundle\Example

services:
#    eugef_php_red_expert_angular.example:
#        class: %eugef_php_red_expert_angular.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
