version: '3.7'
services:
  aliyunddns:
    restart: always
    container_name: AliyunDDNS
    image:
      aliyunddns:latest
    build:
      ./
    volumes:
      - /Volumes/DockerStore/AliyunDDNS/config/:/workdir/Config
      - /tmp/DockerStore/:/tmp/DockerStore/
    networks:
      - dockerstore
    ports:
      - "9119:9119"

networks:
  dockerstore:
    external: true