version: '3.7'
services:
  plex:
    restart: always
    container_name: Plex
    image:
      plex:latest
    build:
      ./
    volumes:
      - /Volumes/DockerStore/Plex/config:/config
      - /Volumes/DockerStore/Plex/transcode:/transcode
      - /Volumes/DockerStore/Plex/data:/data
      - /Volumes/DockerStore/DockerStore/Env/.plexEnv:/volume/.env
      - /tmp/DockerStore/:/tmp/DockerStore/
      - /Volumes/DockerStore/ResilioSync/emby:/data/ResilioSync
      - /Volumes/DockerStore/Aria2/emby:/data/Aria2
    networks:
      - dockerstore
    ports:
      - "9119:32400/tcp"
#      - "3005:3005/tcp"
#      - "8324:8324/tcp"
#      - "32469:32469/tcp"
#      - "1900:1900/udp"
#      - "32410:32410/udp"
#      - "32412:32412/udp"
#      - "32413:32413/udp"
#      - "32414:32414/udp"
    environment:
      TZ: "Asia/Shanghai"
    env_file:
      - /Volumes/DockerStore/DockerStore/Env/.plexEnv

networks:
  dockerstore:
    external: true
