FROM registry.cn-hangzhou.aliyuncs.com/litosrc/php7-swoole:latest
EXPOSE 9100
RUN apt-get update && apt-get -y -q install docker.io
WORKDIR /tmp
ADD ./Docker/DockerStore/docker-compose-Linux-x86_64 /usr/local/bin/docker-compose
RUN chmod 755 /usr/local/bin/docker-compose
WORKDIR /workdir
ADD . .
CMD ["php","Server.php"]