FROM registry.cn-hangzhou.aliyuncs.com/litosrc/ds-ubuntu:latest
EXPOSE 11211
RUN apt-get install memcached libmemcached-tools sasl2-bin -y
ADD dependence/sasl2-memcached.conf /etc/sasl2/memcached.conf
COPY ./docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT [ "/docker-entrypoint.sh" ]