version: '3.7'
services:
  memcached:
    restart: always
    container_name: Memcached
    image:
      memcached:latest
    build:
      ./
    volumes:
      - /opt/DockerStore/Volumes/Memcached/log:/volume/log
      - /opt/DockerStore/Volumes/Memcached/run:/volume/run
    ports:
      - "11211:11211"