version: '3.7'
services:
  phpmyadmin:
    restart: always
    container_name: phpMyAdmin
    image:
      phpmyadmin:latest
    build:
      ./
    networks:
      - dockerstore
    ports:
      - "9102:80"
    environment:
      PMA_ARBITRARY: 1

networks:
  dockerstore:
    external: true