version: '3.7'
services:
  phpmyadmin:
    restart: always
    container_name: phpMyAdmin
    image:
      phpmyadmin:latest
    build:
      ./
    volumes:
      - /Volumes/DockerStore/DockerStore/SSL/:/etc/nginx/ssl/
    networks:
      - dockerstore
    ports:
      - "9102:443"
    environment:
      PMA_ARBITRARY: 1

networks:
  dockerstore:
    external: true