version: '3.7'
services:
  minio:
    restart: always
    container_name: MinIO
    image:
      minio:latest
    build:
      ./
    volumes:
      - /tmp/DockerStore/:/tmp/DockerStore/
      - /Volumes/DockerStore/DockerStore/SSL/:/etc/nginx/ssl/
      - /Volumes/DockerStore/MinIO/data:/volume/data
      - /Volumes/DockerStore/MinIO/config:/volume/config
      - /Volumes/DockerStore/DockerStore/Env/.minioEnv:/volume/.env
    networks:
      - dockerstore
    ports:
      - "9118:9118"
    env_file:
      - /Volumes/DockerStore/DockerStore/Env/.minioEnv

networks:
  dockerstore:
    external: true