parameters:
  redis_servers:
    -
      host: redis
      port: 6379
      name: DockerStore Redis
      password: 123@456@

    - host: redis
      port: 6379
      name: Another Redis
      password: 123@456@

    - host: redis
      port: 6379
      name: Any other Redis
      password: 123@456@

  search_per_page: 50

  locale:            en
  secret:            BoeWP57WFDXdr3U7pj1X1FQYaClrY7ko