FROM registry.cn-hangzhou.aliyuncs.com/litosrc/nginx-php7fpm:latest
EXPOSE 9104
WORKDIR /workdir
ADD dependence/verysync-linux.tar.gz  /workdir
ADD dependence/default /etc/nginx/sites-available/default
RUN mv verysync-* verysync
WORKDIR /workdir/verysync
ADD docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD ["./verysync", "-gui-address", "http://127.0.0.1:8080", "-home", "/volume/config"]