version: '3.7'
services:
  verysync:
    restart: always
    container_name: VerySync
    image:
      verysync:latest
    build:
      ./
    volumes:
      - /Volumes/DockerStore/VerySync/Download:/Download
      - /Volumes/DockerStore/DockerStore/SSL/:/etc/nginx/ssl/
    networks:
      - dockerstore
    ports:
      - "9104:443"

networks:
  dockerstore:
    external: true