FROM registry.cn-hangzhou.aliyuncs.com/litosrc/ds-ubuntu:latest
EXPOSE 9104
WORKDIR /workdir
ADD dependence/verysync-linux.tar.gz  /workdir
RUN mv verysync-* verysync
WORKDIR /workdir/verysync
CMD ["./verysync", "-gui-address", "http://0.0.0.0:9104", "-home", "/volume/config"]