version: '3.7'
services:
  verysync:
    restart: always
    container_name: VerySync
    image:
      verysync:latest
    build:
      ./
    volumes:
      - ~/DockerStore/Volumes/VerySync:/volume
    ports:
      - "9104:9104"