version: '3.7'
services:
  verysync:
    restart: always
    container_name: VerySync
    image:
      verysync:latest
    build:
      ./
    volumes:
      - /Volumes/DockerStore/VerySync:/volume
    networks:
      - dockerstore
    ports:
      - "9104:9104"

networks:
  dockerstore:
    external: true