FROM registry.cn-hangzhou.aliyuncs.com/litosrc/ubuntu:1804
EXPOSE 6379
RUN apt-get update && apt-get install redis -y
ADD dependence/redis.conf /etc/redis.conf
ADD dependence/cli.sh /workdir/cli.sh
ADD ./docker-entrypoint.sh /docker-entrypoint.sh
WORKDIR /workdir
ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD ["redis-server", "/volume/config/redis.conf"]