FROM registry.cn-hangzhou.aliyuncs.com/litosrc/ds-ubuntu:latest
EXPOSE 6379
RUN apt-get install redis-server -y
ADD dependence/redis.conf /etc/redis/redis.conf
CMD ["redis-server", "/etc/redis/redis.conf"]