version: '3.7'
services:
  redis:
    restart: always
    container_name: Redis
    image:
      redis:latest
    build:
      ./
    volumes:
      - ~/DockerStore/Volumes/Redis/db:/volume/db
      - ~/DockerStore/Volumes/Redis/log:/volume/log
    ports:
      - "6379:6379"