version: '3.7'
services:
  redis:
    restart: always
    container_name: Redis
    image:
      redis:latest
    build:
      ./
    volumes:
      - /Volumes/DockerStore/Redis/db:/volume/db
      - /Volumes/DockerStore/Redis/log:/volume/log
      - /Volumes/DockerStore/Redis/config:/volume/config
      - /tmp/DockerStore/:/tmp/DockerStore/
    ports:
      - "6379:6379"