version: '3.7'
services:
  nettoftp:
    restart: always
    container_name: NetToFtp
    image:
      nettoftp:latest
    build:
      ./
    volumes:
      - ~/DockerStore/Volumes/NetToFtp/config/sites-available/:/etc/nginx/sites-available/
      - ~/DockerStore/Volumes/NetToFtp/config/php-fpm/:/etc/php/7.2/fpm/
      - ~/DockerStore/Volumes/NetToFtp/workdir/:/workdir/
    ports:
      - "9108:80"