FROM registry.cn-hangzhou.aliyuncs.com/litosrc/nginx-php7fpm:latest
EXPOSE 80
ADD ./docker-entrypoint.sh /docker-entrypoint.sh
ADD ./dependence/ /tmp/dependence/
WORKDIR /workdir
ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD ["nginx", "-g", "daemon off;"]