FROM registry.cn-hangzhou.aliyuncs.com/litosrc/phpfpm:7.2
EXPOSE 443
ADD ./docker-entrypoint.sh /docker-entrypoint.sh
ADD ./dependence/ /tmp/dependence/
WORKDIR /workdir
ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD ["nginx", "-g", "daemon off;"]