version: '3.7'
services:
  chronograf:
    restart: always
    container_name: Chronograf
    image:
      chronograf:latest
    build:
      ./
    volumes:
      - /Volumes/DockerStore/Chronograf/data/:/var/lib/chronograf
      - /Volumes/DockerStore/DockerStore/SSL/:/workdir/ssl/
    networks:
      - dockerstore
    ports:
      - "9115:8888"

networks:
  dockerstore:
    external: true