version: '3.7'
services:
  dokuwiki:
    restart: always
    container_name: DokuWiki
    image:
      dokuwiki:latest
    build:
      ./
    volumes:
      - /Volumes/DockerStore/DokuWiki/workdir/:/workdir/
      - /Volumes/DockerStore/DockerStore/SSL/:/etc/nginx/ssl/
    networks:
      - dockerstore
    ports:
      - "9106:443"

networks:
  dockerstore:
    external: true