FROM registry.cn-hangzhou.aliyuncs.com/litosrc/ds-php-nginx:latest
WORKDIR /workdir
ADD ./docker-entrypoint.sh /docker-entrypoint.sh
ADD ./dependence /tmp/dependence
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]