version: '3.7'
services:
  dokuwiki:
    restart: always
    container_name: DokuWiki
    image:
      dokuwiki:latest
    build:
      ./
    volumes:
      - /opt/DockerStore/Volumes/DokuWiki/workdir/:/workdir/
    ports:
      - "9106:80"