FROM registry.cn-hangzhou.aliyuncs.com/litosrc/phpfpm:7.2
WORKDIR /workdir
EXPOSE 9103
ADD dependence/default /etc/nginx/sites-available/default
RUN curl -fsSL https://code.aliyun.com/lit/resource/raw/master/dockerstore/node-v12.13.0-linux-x64.tar.xz -o node-v12.13.0-linux-x64.tar.xz && \
    tar xvf node-v12.13.0-linux-x64.tar.xz && \
    mv ./node-v12.13.0-linux-x64 /usr/local/lib/nodejs && \
    ln -s /usr/local/lib/nodejs/bin/node /usr/bin/node && \
    ln -s /usr/local/lib/nodejs/bin/npm /usr/bin/npm && \
    npm install whistle -g --registry=https://registry.npm.taobao.org
ADD ./docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD ["/usr/local/lib/nodejs/bin/w2","--host","0.0.0.0","--port","8889","run"]