version: '3.7'
services:
  whistle:
    restart: always
    container_name: Whistle
    image:
      whistle:latest
    build:
      ./
    volumes:
      - /Volumes/DockerStore/Whistle:/volume
    networks:
      - dockerstore
    ports:
      - "9103:9103"

networks:
  dockerstore:
    external: true