version: '3.7'
services:
  whistle:
    restart: always
    container_name: Whistle
    image:
      whistle:latest
    build:
      ./
    volumes:
      - /Volumes/DockerStore/Whistle:/volume
      - /Volumes/DockerStore/DockerStore/SSL/:/etc/nginx/ssl/
    networks:
      - dockerstore
    ports:
      - "9103:443"
      - "8889:8889"

networks:
  dockerstore:
    external: true