FROM registry.cn-hangzhou.aliyuncs.com/litosrc/phpfpm:7.2
EXPOSE 9111
WORKDIR /workdir
ADD dependence/default /etc/nginx/sites-available/default
ADD ./docker-entrypoint.sh /docker-entrypoint.sh
ADD ./dependence /tmp/dependence
ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD ["./frpc", "-c", "/volume/config/frpc.ini"]
