version: '3.7'
services:
  frpclient:
    restart: always
    container_name: FrpClient
    image:
      frpclient:latest
    build:
      ./
    volumes:
      - /Volumes/DockerStore/FrpClient/config/:/volume/config/
      - /Volumes/DockerStore/FrpClient/log/:/volume/log/
      - /tmp/DockerStore/:/tmp/DockerStore/
      - /Volumes/DockerStore/DockerStore/SSL/:/etc/nginx/ssl/
    networks:
      - dockerstore
    ports:
      - "9111:443"

networks:
  dockerstore:
    external: true