FROM registry.cn-hangzhou.aliyuncs.com/litosrc/ds-ubuntu:latest
EXPOSE 7000
WORKDIR /workdir
ADD ./docker-entrypoint.sh /docker-entrypoint.sh
ADD ./dependence /tmp/dependence
ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD ["./frpc", "-c", "/volume/config/frpc.ini"]
