version: '3.7'
services:
  phpmyadmin:
    restart: always
    container_name: phpMyAdmin
    image:
      phpmyadmin:latest
    build:
      ./
    volumes:
      - /volume/phpMyAdmin:/volume
    ports:
      - "9002:80"
    environment:
      PMA_ARBITRARY: 1