version: '3.7'
services:
  webssh:
    restart: always
    container_name: WebSSH
    image:
      webssh:latest
    build:
      ./
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Volumes/DockerStore/DockerStore/SSL/:/workdir/ssl/
      - /Volumes/DockerStore/WebSSH/sshConfig/:/root/.ssh/
      - /tmp/DockerStore/:/tmp/DockerStore/
    networks:
      - dockerstore
    ports:
      - "9112:9112"

networks:
  dockerstore:
    external: true