FROM ubuntu:18.04
EXPOSE 8080
WORKDIR /workdir
ADD dependence/resilio-sync.deb .
RUN mkdir -p /volume/config && mkdir /volume/sync && apt-get install ./resilio-sync.deb
CMD ["rslsync","--webui.listen","0.0.0.0:9001","--storage","/volume/config","--log","/dev/null","--nodaemon"]