version: '3.7'
services:
  nextcloud:
    restart: always
    container_name: NextCloud
    image:
      nextcloud:latest
    build:
      ./
    volumes:
      - /Volumes/DockerStore/NextCloud/workdir/:/workdir/
      - /Volumes/DockerStore/DockerStore/SSL/:/etc/nginx/ssl/
      - /tmp/DockerStore/:/tmp/DockerStore/
    networks:
      - dockerstore
    ports:
      - "9109:443"

networks:
  dockerstore:
    external: true