version: '3.7'
services:
  nextcloud:
    restart: always
    container_name: NextCloud
    image:
      nextcloud:latest
    build:
      ./
    volumes:
      - /volume/NextCloud/data:/workdir/data
      - /volume/NextCloud/config:/workdir/config
    ports:
      - "9006:443"