FROM registry.cn-hangzhou.aliyuncs.com/litosrc/nginx-php7fpm:latest
WORKDIR /workdir
RUN apt-get update && apt-get -y install php-intl php-imagick php-apcu
ADD ./docker-entrypoint.sh /docker-entrypoint.sh
ADD ./dependence /tmp/dependence
EXPOSE 443
ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD ["nginx", "-g", "daemon off;"]