FROM registry.cn-hangzhou.aliyuncs.com/litosrc/ds-ubuntu:latest
EXPOSE 8086
WORKDIR /workdir
RUN apt-get update && apt-get install wget -y
RUN wget https://dl.influxdata.com/influxdb/releases/influxdb_1.7.9_amd64.deb && dpkg -i influxdb_1.7.9_amd64.deb
ADD ./dependence /tmp/dependence
ADD ./docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD ["influxd", "-config", "/etc/influxdb/influxdb.conf"]