version: '3.7'
services:
  mysql57:
    restart: always
    container_name: MySQL57
    image:
      mysql57:latest
    build:
      ./
    volumes:
      - /Volumes/DockerStore/MySQL57/mysql:/var/lib/mysql
      - /Volumes/DockerStore/MySQL57/log:/var/log/mysql
      - /Volumes/DockerStore/DockerStore/SSL/:/etc/nginx/ssl/
    networks:
      - dockerstore
    ports:
      - "3306:3306"
      - "9105:443"

networks:
  dockerstore:
    external: true