FROM registry.cn-hangzhou.aliyuncs.com/litosrc/phpfpm:7.2
EXPOSE 3306
WORKDIR /tmp
RUN curl -fsSL https://code.aliyun.com/lit/resource/raw/master/dockerstore/phpMyAdmin-4.9.1-all-languages.tar.xz -o phpMyAdmin-4.9.1-all-languages.tar.xz && \
    tar xvf phpMyAdmin-4.9.1-all-languages.tar.xz && mv phpMyAdmin-4.9.1-all-languages/* /workdir
WORKDIR /workdir
RUN apt-get update && apt-get install mysql-server=5.7* -y
RUN mv /var/lib/mysql /var/lib/mysql-files
ADD dependence/config.inc.php ./config.inc.php
ADD dependence/mysqld.cnf /etc/mysql/mysql.conf.d/mysqld.cnf
ADD dependence/default /etc/nginx/sites-available/default
COPY ./docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD ["nginx", "-g", "daemon off;"]